Added support for android view intent action
KasemJaffer/receive_sharing_intent pull request #160
Opened 2021-05-04 09:08 UTC by odam1

2021-09-01 08:19 UTC, GRBurst requested changes

2021-09-01 08:19 UTC, GRBurst commented on example/ios/Runner.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = BN2V9FW285;
I think this is set to "" on purpose ;-) I suggest leaving it out.
```suggestion
				DEVELOPMENT_TEAM = "";
```

2021-09-01 08:19 UTC, GRBurst commented on example/ios/Runner.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = "com.odamsoft.sharing.Sharing-Extension";
Keep it like `com.kasem....`
```suggestion
				PRODUCT_BUNDLE_IDENTIFIER = "com.kasem.sharing.Sharing-Extension";
```

2021-09-01 08:22 UTC, GRBurst commented
I added some representative change request, but there is more of your personal ids that need to be reverted ;-)

2021-10-30 10:51 UTC, closed without merging

2022-02-07 11:53 UTC, filipenanclarez commented
intent.action.VIEW is handled in package as url type. When user try open a file, android system send the uri of this file to intent.

if you need open file with dart:io functions like readAdBytes or readAsString, you should convert the Uri to full path. You can do this with [uri_to_file](https://pub.dev/packages/uri_to_file) package.

So, you can handle action.VIEW with this code in flutter side:

```
import 'package:uri_to_file/uri_to_file.dart';
...
// For sharing or opening urls/text coming from outside the app while the app is closed
ReceiveSharingIntent.getInitialText().then((String? value) async {
    String _sharedText = value ?? "";
    debugPrint('path of file: ${Uri.parse(_sharedText).path}');
    File file = await toFile(_sharedText);
    var fileContent = await file.readAsString();
    ...
});
```